base_url: https://www.uvsultra.online
list_url: https://www.uvsultra.online/listing_cards.php
card_link_selector: 'div.card_image'
pagination_selector: 'ul.pagination li a[href*="listing_cards.php"]'
rate_limit_seconds: 0.3

selectors:
  name: 'div.card_title h1'
  type: 'div.card_division.cd1 br ~ *:nth-of-type(1)'
  rarity: 'div.card-important-info'
  cost: ''
  attack: ''
  health: ''
  text: 'div.card_text'
  set_code: ''
  set_name: 'div.card_division.cd1 a'
  number: 'div.card_division.cd1 span'
  image_url: 'img.mini_image::attr(src)'